//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsWebService_client.CalcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcRef.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add", ReplyAction="*")]
        double add(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add", ReplyAction="*")]
        System.Threading.Tasks.Task<double> addAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subtract", ReplyAction="*")]
        double subtract(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subtract", ReplyAction="*")]
        System.Threading.Tasks.Task<double> subtractAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiply", ReplyAction="*")]
        double multiply(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiply", ReplyAction="*")]
        System.Threading.Tasks.Task<double> multiplyAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/divide", ReplyAction="*")]
        double divide(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/divide", ReplyAction="*")]
        System.Threading.Tasks.Task<double> divideAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : CsWebService_client.CalcRef.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<CsWebService_client.CalcRef.CalculatorWebServiceSoap>, CsWebService_client.CalcRef.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double add(double a, double b) {
            return base.Channel.add(a, b);
        }
        
        public System.Threading.Tasks.Task<double> addAsync(double a, double b) {
            return base.Channel.addAsync(a, b);
        }
        
        public double subtract(double a, double b) {
            return base.Channel.subtract(a, b);
        }
        
        public System.Threading.Tasks.Task<double> subtractAsync(double a, double b) {
            return base.Channel.subtractAsync(a, b);
        }
        
        public double multiply(double a, double b) {
            return base.Channel.multiply(a, b);
        }
        
        public System.Threading.Tasks.Task<double> multiplyAsync(double a, double b) {
            return base.Channel.multiplyAsync(a, b);
        }
        
        public double divide(double a, double b) {
            return base.Channel.divide(a, b);
        }
        
        public System.Threading.Tasks.Task<double> divideAsync(double a, double b) {
            return base.Channel.divideAsync(a, b);
        }
    }
}
